kind: pipeline
type: kubernetes
name: default
trigger:
  branch:
    - master
steps:

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    repo: registry.cn-hangzhou.aliyuncs.com/pivotstudio/drone-master-config
    mtu: 1400
    username: 
      from_secret: docker_user_name
    password: 
      from_secret: docker_pass
