kind: pipeline
type: kubernetes
name: default
trigger:
  branch:
    - master
steps:
  - name: start comment
    image: jmccann/drone-github-comment:1
    settings:
      message: <h2><a target="_blank" href="${DRONE_SYSTEM_PROTO}://${DRONE_SYSTEM_HOST}/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/">CI Is Running⌛⌛⌛</a></h2>  <b>click the link above for details </b>
      update: true
    when:
      ref:
        include:
        - refs/pull/**
  - name: go test & build
    image: golang
    commands:
    - echo "<h2><a target=\"_blank\" href=\"$DRONE_SYSTEM_PROTO://$DRONE_SYSTEM_HOST/$DRONE_REPO/$DRONE_BUILD_NUMBER/\">CI Failed❌❌❌</a></h2>\n  \nclick the link above for details  \n">coverage.txt
    - go env -w GO111MODULE=on
    - go env -w GOPROXY=https://goproxy.cn,direct
    - export CI=true
    - go test ./...  -covermode=atomic
    - go build ./...
    - go build -o app -v main.go
    - echo "<h2><a target=\"_blank\" href=\"$DRONE_SYSTEM_PROTO://$DRONE_SYSTEM_HOST/$DRONE_REPO/$DRONE_BUILD_NUMBER/\">CI Success✔️✔️✔️</a></h2>\n  \n<h3>coverages</h3>  \n">coverage.txt
    - cat /cov/log.txt|grep ok>>coverage.txt
    when:
      ref:
        include:
        - refs/pull/**
        - refs/heads/master
  - name: comment
    image: jmccann/drone-github-comment:1
    settings:
      message_file: coverage.txt
      update: true
    depends_on:
      - "go test & build"
    when:
      ref:
        include:
        - refs/pull/**
  - name: failed comment
    image: jmccann/drone-github-comment:1
    settings:
      message_file: coverage.txt
      update: true
    depends_on:
      - "go test & build"
    when:
      ref:
        include:
        - refs/pull/**
      status:
      - failure
  - name: docker ci
    image: plugins/docker
    depends_on:
      - "go test & build"
    settings:
      mirror: https://jtkrmusq.mirror.aliyuncs.com
      repo: registry.cn-hangzhou.aliyuncs.com/pivotstudio/drone-master-config
      registry: registry.cn-hangzhou.aliyuncs.com
      cache_from: registry.cn-hangzhou.aliyuncs.com/pivotstudio/drone-master-config:latest
      mtu: 1400
      username: 
        from_secret: docker_user_name
      password: 
        from_secret: docker_pass
      tags:
        - latest
        - build-${DRONE_BUILD_NUMBER} 
    when:
      branch:
       - master
      event:
      - push
  - name: deploy
    image: bh90210/dron8s:latest
    settings:
      yaml: ./deploy/drone-ext.yaml
      build_tag: build-${DRONE_BUILD_NUMBER}
    depends_on:
      - "docker ci"
    when:
      branch:
       - master
      event:
      - push
